### ISSUE TITLE
Higher precision for NMEA generation

### ISSUE THREAD

**Issue by jimwormold** [dassencio/nmeagen#1]
Hi

Thanks for a great tool! 

I was wondering if it would be possible to increase the precision when exporting to an nmea log. The current precision is set to 3 (var m_latitudePrecision=3). I am trying to emulate a very slow moving object, and I think that my tracking calculations are failing because I am losing out on the precision (the NMEA N, and W coords remain the same for multiple sentences and then jump a either N or W, rather than a diagonal track).

Thanks

**Comment by dassencio** [comment]
@jimwormold: Thank you! :-)

Your use case is very specific to the situation you are trying to simulate, and since you can build a modified version of the tool with a custom value of `m_latitudePrecision`, it makes more sense to go that way. From the other issue you opened (https://github.com/dassencio/nmeagen/issues/2), it seems you tried that already -- did it work?

By the way, please keep in mind that increasing the precision of the generated positions will lead to NMEA logs which are not physically realistic as they would be equivalent to having GPS positions  obtained with accuracies of a few centimeters or less.

**Comment by jimwormold** [comment]
Yes, I have managed to set it up and it's working nicely now (I just needed to find a linux machine!).

I agree that my use-case is specific, but it actually is quite common for RTK GPS to operate to centimetre accuracy.

Happy to close!

**Comment by dassencio** [comment]
> Yes, I have managed to set it up and it's working nicely now (I just needed to find a linux machine!).

Awesome!

> I agree that my use-case is specific, but it actually is quite common for RTK GPS to operate to centimetre accuracy.

Well, I stand corrected. The vast majority of the GPS data I worked with was obtained from sensors present in phones and cars. Those are usually far less accurate than that :-)
